### ISSUE TITLE
Missing getmempoolentry

### ISSUE THREAD

**Issue by FrozenPrincess** [btcsuite/btcrpcclient#113]
Here's a sample call:

`getmempoolentry abed2bc7cc77a4bc342a67e29da974b9cc69d47afa6279463d916009b1bcb6a3`
￼
{
  "size": 372,
  "fee": 0.00008280,
  "modifiedfee": 0.00008280,
  "time": 1484977137,
  "height": 1085243,
  "startingpriority": 541889.8421052631,
  "currentpriority": 568809.6710526316,
  "descendantcount": 1,
  "descendantsize": 372,
  "descendantfees": 8280,
  "ancestorcount": 1,
  "ancestorsize": 372,
  "ancestorfees": 8280,
  "depends": [
  ]
}
```

In my particular use-case, the fields I need are `ancestorsize` and `ancestorfees` as I'm trying to compute the feerate to guestimate if it'll confirm. I notice these fields are also missing from btcjson.GetRawMempoolVerboseResult.  So it'd be nice if they were also made complete

**Comment by dajohi** [comment]
https://github.com/btcsuite/btcd/pull/905

**Comment by davecgh** [comment]
@dajohi: For reference, even if you add those fields to the result as 905 currently does, none of the ancestor/descendant information is available to populate the results.  The mempool doesn't current keep track of that information.

**Comment by dajohi** [comment]
@FrozenPrincess Are you able to give #117 a try?
