### ISSUE TITLE
GetTransaction includeWatchOnly

### ISSUE THREAD

**Issue by cpacia** [btcsuite/btcrpcclient#121]
I have need to access watch only transactions but the GetTransaction function currently passes nil into the btcjson NewGetTransactionCmd constructor (meaning do not return watch only). Is there any objection to a PR exposing the the bool in the GetTransaction and GetTransactionAsync parameters?

**Comment by jrick** [comment]
sounds fine to me.

**Comment by jrick** [comment]
although we have traditionally used multiple functions when optional parameters can be passed, in this case we'd need to do the same. don't change the signature of GetTransaction(Async).

**Comment by davecgh** [comment]
This issue was moved to btcsuite/btcd#1004
