### ISSUE TITLE
Implementation of addr method?

### ISSUE THREAD

**Issue by magestican** [btcsuite/btcrpcclient#49]
I was looking into your code and I see that this method is not implemented, could you add this in future updates?

**Comment by davecgh** [comment]
I'm not sure I'm following which method you are referring to.

There is already [GetNewAddress](http://godoc.org/github.com/btcsuite/btcrpcclient#Client.GetNewAddress) (pull request #47 will add the account parameter).

Also, if you want to get the most recently generated address, there is [GetAccountAddress](http://godoc.org/github.com/btcsuite/btcrpcclient#Client.GetAccountAddress).

**Comment by magestican** [comment]
I see yes thanks, although I cannot find a way of getting more information out of an Account, have you implemented something like that? To know if an address is actually a daemon, or a bot,etc.

**Comment by davecgh** [comment]
Oh, I see what you're after.  That is something completely different.  This package is for RPC access via JSON-RPC and the methods I linked are for Bitcoin addresses, not network addresses.

What you're talking about is the peer-to-peer wire protocol.  You want the [wire](https://github.com/btcsuite/btcd/tree/master/wire) package from btcd to speak the p2p protocol.  Then in particular the [MsgAddr](http://godoc.org/github.com/btcsuite/btcd/wire#MsgAddr) type which houses a [NetAddress](http://godoc.org/github.com/btcsuite/btcd/wire#NetAddress).

See [this](https://github.com/btcsuite/btcd/issues/6#issuecomment-37146524) comment for example usage of that package.
