### ISSUE TITLE
verboseTx param make GetBlockVerbose and GetBlockVerboseAsync fail

### ISSUE THREAD

**Issue by conejoninja** [btcsuite/btcrpcclient#59]
This line : https://github.com/btcsuite/btcrpcclient/blob/master/chain.go#L143

**SYMPTONS**
Calling function getBlockVerbose or GetBlockVerboseAsync returns an error, no matter which parameters are used. Error message at the end

**HOW TO REPRODUCE**
```go
hash, err := client.GetBlockHash(100)
if err != nil {
	log.Fatal(err)
}

block, err := client.GetBlock(hash)
if err != nil { // err is nil
	log.Fatal(err) 
}
blockverbose, err := client.GetBlockVerbose(hash, true) //no matter is true or false is used, error is triggered always
if err != nil { 
	log.Fatal(err) // this is triggered
}
```

**NOTE** 

Same error message is achieved directly with bitcoin-cli if a second bool parameter (verboseTx) is used

All of these fails
```bash
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a true true
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a true false
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a false true
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a false false
```

These works
```bash
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a true
bitcoin-cli getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a false
```

Thus forcing verboseTx to nil, "fix" the issue, but verboseTx is still in the code. I'm still reviewing the code so I'm not sure about the consequences of this change.

**ERROR MESSAGE**
error: {"code":-1,"message":"getblock "hash" ( verbose )

If verbose is false, returns a string that is serialized, hex-encoded data for block 'hash'.
If verbose is true, returns an Object with information about block <hash>.
Arguments:
1. "hash"          (string, required) The block hash
2. verbose           (boolean, optional, default=true) true for a json object, false for the hex encoded data

Result (for verbose = true):
{
  "hash" : "hash",     (string) the block hash (same as provided)
  "confirmations" : n,   (numeric) The number of confirmations, or -1 if the block is not on the main chain
  "size" : n,            (numeric) The block size
  "height" : n,          (numeric) The block height or index
  "version" : n,         (numeric) The block version
  "merkleroot" : "xxxx", (string) The merkle root
  "tx" : [               (array of string) The transaction ids
     "transactionid"     (string) The transaction id
     ,...
  ],
  "time" : ttt,          (numeric) The block time in seconds since epoch (Jan 1 1970 GMT)
  "nonce" : n,           (numeric) The nonce
  "bits" : "1d00ffff", (string) The bits
  "difficulty" : x.xxx,  (numeric) The difficulty
  "previousblockhash" : "hash",  (string) The hash of the previous block
  "nextblockhash" : "hash"       (string) The hash of the next block
}

Result (for verbose=false):
"data"             (string) A string that is serialized, hex-encoded data for block 'hash'.

Examples:
> bitcoin-cli getblock "00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getblock", "params": ["00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/
"}

**Comment by davecgh** [comment]
Please make sure you have `btcrpcclient` and `btcd` at the latest versions.  I just tested this and it's working correctly:

```Go
	blockVerbose, err := client.GetBlockVerbose(hash, true)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("%v\n", spew.Sdump(blockVerbose))
```

> 2015/07/04 03:04:29 (*btcjson.GetBlockVerboseResult)(0xc0820760c0)({
>  Hash: (string) (len=64) "000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a",
>  Confirmations: (uint64) 363663,
>  Size: (int32) 215,
>  Height: (int64) 100,
> ...

Using btcctl:
> $ btcctl getblock 000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a true false
> {
>   "hash": "000000007bc154e0fa7ea32218a72fe2c1bb9f86cf8c9ebf9a715ed27fdb229a",
>   "confirmations": 363664,
>   "size": 215,
>   "height": 100,
>   ...
> }


btcd repository:
> $ git rev-parse HEAD
> 5bb6cd7d4456baa0fa53abe297bca3f193909270

btcrpcclient repository:
> $ git rev-parse HEAD
> 7cb04ae6db6d10d1716b575485b4802423746c9f

**Comment by conejoninja** [comment]
Ok, my bad then. I though it was compatible with bitcoind (official). Will switch to btcd then.
