### ISSUE TITLE
GetBlock() returns *errors.errorString instead of *RPCError

### ISSUE THREAD

**Issue by scisci** [btcsuite/btcrpcclient#60]
A call to GetBlock() where the block has not been confirmed yet returns a raw json error instead of an RPCError:

{"result":null,"error":{"code":-5,"message":"Block not found"},"id":2}

Not sure but briefly looking through the code, if status code isn't between 200 and 300 then it just returns raw json. Here's my config:

connCfg := &btcrpcclient.ConnConfig{
		Host:         config.Host,
		Endpoint:     "ws",
		User:         config.User,
		Pass:         config.Pass,
		HTTPPostMode: true,
		//Certificates: certs,
		DisableTLS: true,
	}

**Comment by davecgh** [comment]
Thanks for the report.  What server are you communicating with?  I ask because I just tried this with btcd and it appears to work correctly:

```Go
	// Try to get block that doesn't exist.
	hash := &wire.ShaHash{}
	block, err := client.GetBlock(hash)
	if err != nil {
		log.Fatalf("type: %T, error: %[1]v", err)
	}
	log.Print(block.Sha())
```

> 2015/07/11 23:19:45 type: *btcjson.RPCError, error: -5: Block not found

**Comment by scisci** [comment]
I'm using bitcoin-qt:
```
hash, err := wire.NewShaHashFromStr(rawTx.BlockHash)
block, err := client.GetBlock(hash)
if err != nil {
  fmt.Println(reflect.TypeOf(err))
}
```
I'll try to look into it a bit more today.

**Comment by scisci** [comment]
Still seeing this issue, connecting locally using bitcoing-qt and also connecting to bitcoin core. Its a bit of a problem for me because it makes error detection harder. Any idea what might be the problem, or is this a core issue?

**Comment by dajohi** [comment]
@scisci Still a problem?  What version of go?

**Comment by davecgh** [comment]
I was able to reproduce this and will submit a PR that fixes it shortly.
