### ISSUE TITLE
Go get btcrpcclient fails due to arg list error

### ISSUE THREAD

**Issue by sundance30203** [btcsuite/btcrpcclient#69]
When I try to install/get btcrpcclient, the following error occurs immediately

$ go get github.com/btcsuite/btcrpcclient
# github.com/btcsuite/btcrpcclient
../goprojects/src/github.com/btcsuite/btcrpcclient/rawtransactions.go:247: not enough arguments in call to btcjson.NewCreateRawTransactionCmd
../goprojects/src/github.com/btcsuite/btcrpcclient/rawtransactions.go:555: not enough arguments in call to btcjson.NewSearchRawTransactionsCmd
../goprojects/src/github.com/btcsuite/btcrpcclient/rawtransactions.go:601: not enough arguments in call to btcjson.NewSearchRawTransactionsCmd

**Comment by davecgh** [comment]
Looks like your `btcjson` is out of date.  Try `go get -u -v github.com/btcsuite/btcrpcclient` which will cause the deps to be udpated.
