### ISSUE TITLE
About support other coins

### ISSUE THREAD

**Issue by qunxyz** [btcsuite/btcrpcclient#78]
Great job. But I found a problem here, it can't support other coins, while it should. cause btcutil would validated data only belong to bitcoin, like address, etc. I have to add a method SendCmd in infrastructure.go, and override every api I need in my code. could you just make api return a map result, or don't validate data?  Thanks

**Comment by davecgh** [comment]
You should be able to create your own `chaincfg.ChainParams` with the appropriate values for your needs so that btcutil will work with the addresses.

**Comment by soggie** [comment]
Here's what I used for dogecoin @qunxyz 

```
var DogeMainParam = &chaincfg.Params{
	Name:             "mainnet",
	PubKeyHashAddrID: 0x1E,
	ScriptHashAddrID: 0x16,
}

var DogeTestParam = &chaincfg.Params{
	Name:             "testnet3",
	PubKeyHashAddrID: 0x71,
	ScriptHashAddrID: 0xC4,
}
```

**Comment by qunxyz** [comment]
Thanks @soggie. I don't need it now, but good for others
