### ISSUE TITLE
API Calls Block Forever After Many Requests

### ISSUE THREAD

**Issue by csmcanarney** [btcsuite/btcrpcclient#79]
While writing a long-running application that sends many requests to btcd, I noticed that eventually API calls would block forever.

I am able to reproduce the issue with a small [example program](https://gist.github.com/csmcanarney/a90b58de8d135ba31643f69c43ba4e16#file-test-go), which I've uploaded together with the relevant logs. After running for little over an hour and making roughly ~~250,000~~ 1,000,000 requests, calls to the API methods of `btcrpcclient.Client` block, stalling the program. However, the connection to btcd does not appear to be lost as the notification handlers are still being called. Also, btcd still responds to requests made with btcctl.

The complete btcd log was too large for Gist, but if necessary I can upload it somewhere else. I am using the latest versions of btcd (btcsuite/btcd@6e644855f54d269f41785b01c3544d13f11e5ecc) and btcrpcclient (btcsuite/btcrpcclient@64922553b5c21f333438edaed6e0ba2b5a7760ee).

I will continue to try to narrow down the problem, but I thought I'd ask in the meantime in case I'm just making some silly mistake. Am I using btcrpcclient incorrectly? Should I be rate limiting my requests to btcd perhaps? Any help would be greatly appreciated!

**Comment by csmcanarney** [comment]
I've simplified the [example program](https://gist.github.com/csmcanarney/b80e87e1905af3d9b0e8679584049e58) to only make a single API call per iteration in a single goroutine. The 1,000,000th API call reliably fails with every API method I've tried so far.

**Comment by csmcanarney** [comment]
The problem stems from btcd returning RPC identifiers that are ≥1,000,000 in scientific notation, e.g. `1000604` becomes `1.000604e+06`. In my interpretation of the JSON-RPC specification that should be fine as the two values are strictly equal in JavaScript, so it's up to btcrpcclient to handle it properly.

**Comment by davecgh** [comment]
Nice find and thanks for hunting it down!  Let me take a look at this real quick.  I think the right way to fix this is probably to make sure btcd doesn't return scientific notation for the ID.

**Comment by davecgh** [comment]
Also, for reference, it's easy to see the warning if you enable logging in the client.

```Go
	backendLogger := btclog.NewDefaultBackendLogger()
	rpccLogger := btclog.NewSubsystemLogger(backendLogger, "RPCC: ")
	btcrpcclient.UseLogger(rpccLogger)
```

>22:37:43 2016-08-07 [WRN] RPCC: Remote server sent invalid message: json: cannot unmarshal number 1e+06 into Go value of type uint64
