### ISSUE TITLE
`GetBlockVerbose` is broken for bitcoin core

### ISSUE THREAD

**Issue by FrozenPrincess** [btcsuite/btcrpcclient#90]
GetBlockVerbose takes an argument `verboseTx bool`, and make the rpc call

```
{"jsonrpc":"1.0","method":"getblock","params":["0000000000000000023ce2ceba757ccca3d3ee4938608f37f1e73cd4ec3d6d59",true,verboseTx],"id":1}
```

However bitcoin core's `getblock` only takes one argument, so this gives an error

**Comment by davecgh** [comment]
Fixed by #94.
